name: "Books Signed by People Who Didn't Write Them"
favicon: null
layout_spectrum: 0.8075853160116822
typography_spectrum: 0.6070993361063302
title: "Book by People who Didn't Write Them"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ffec'
    - '#11110f'
    - '#ea2829'
    - '#7b5e5a'
    - '#d98f82'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
